const os =  require("os")
console.log("OS platform : ",os.platform())
console.log("OS CPU architecture : ",os.arch())
console.log("OS hostname : ",os.hostname())
console.log("OS Release : ",os.release())
console.log("OS Free Memory : ",os.freemem()/(1024*1024*1024))
console.log("OS Total Memory : ",os.totalmem()/(1024*1024*1024))
console.log("OS Uptime : ",os.uptime()/(60*60))
console.log("OS User info : ",os.userInfo())
console.log("OS Network Interfaces : ",os.networkInterfaces())
// console.log("OS EOL : ",os.EOL)
// console.log("OS Constants : ",os.constants)